feat(options): support htmlWebpackPlugin options & replace [name] in …
mutualofomaha/multipage-webpack-plugin pull request #34
Opened 2017-06-29 04:52 UTC by xiaoiver

1. support other htmlWebpackPlugin options, like inject, favicon
2. also replace [name] in htmlTemplatePath

2017-07-05 14:57 UTC, TheLarkInn commented
@xiaoiver This is a really great idea to have an escape hatch for the rest of the options.

Could you please add a few test cases for the specific features you are leveraging from htmlWebpackPluginOptions?

2017-07-05 14:59 UTC, TheLarkInn requested changes

2017-07-05 14:59 UTC, TheLarkInn commented on src/plugin.js
> +    htmlWebpackPluginOptions: htmlWebpackPluginOptions || {}
I'd like to have some tests specific for a few of the features used here. I know there are a lot so just a few would be good. 

Also could I convince you to submit an issue (as a reminder to us) to add better tests for html-webpack-plugin options overall.

2017-07-07 02:33 UTC, xiaoiver commented on src/plugin.js
> +    htmlWebpackPluginOptions: htmlWebpackPluginOptions || {}
OK, I'll add a test case for some html-webpack-plugin options maybe like favicon, minify...

2017-07-07 03:25 UTC, xiaoiver commented
I added a simple test case for `minify` and `favicon` options in html-webpack-plugin. Is there anything I should complement？

2017-07-07 03:30 UTC, TheLarkInn commented on src/plugin.js
> +    htmlWebpackPluginOptions: htmlWebpackPluginOptions || {}
This looks wonderful. Very well done.

2017-07-07 03:31 UTC, TheLarkInn approved these changes

2017-07-07 03:31 UTC, merged

2017-07-07 03:32 UTC, TheLarkInn commented
Thank you @xiaoiver for the contribution. We use semantic release to automatically publish so please keep an eye on master branch Travis build to see when update is published